apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
      - name: application-service
        # The build script will replace PLACEHOLDER_PROJECT_ID with your secret
        image: asia-south1-docker.pkg.dev/PLACEHOLDER_PROJECT_ID/devops/application-service:latest
        ports:
        - containerPort: 3001
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    app: application-service
  ports:
  - port: 80
    targetPort: 3001
  type: ClusterIP
